// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradingProject.Persistence.Infrastructure.Persistence;

#nullable disable

namespace TradingProject.Persistence.Infrastructure.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260514100000_RemoveUsdtColumnsSuffix")]
    partial class RemoveUsdtColumnsSuffix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradingProject.Persistence.Domain.Entities.Opportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Acted")
                        .HasColumnType("boolean")
                        .HasColumnName("acted");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Signal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signal");

                    b.Property<double?>("StopLossPct")
                        .HasColumnType("double precision")
                        .HasColumnName("stop_loss_pct");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.Property<double?>("TargetPct")
                        .HasColumnType("double precision")
                        .HasColumnName("target_pct");

                    b.Property<string>("ValidationReason")
                        .HasColumnType("text")
                        .HasColumnName("validation_reason");

                    b.HasKey("Id");

                    b.ToTable("opportunities", (string)null);
                });

            modelBuilder.Entity("TradingProject.Persistence.Domain.Entities.PortfolioSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("DailyPnl")
                        .HasColumnType("double precision")
                        .HasColumnName("daily_pnl");

                    b.Property<double>("Free")
                        .HasColumnType("double precision")
                        .HasColumnName("free");

                    b.Property<int>("PositionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("positions_count");

                    b.Property<double>("Total")
                        .HasColumnType("double precision")
                        .HasColumnName("total");

                    b.Property<double>("TotalPnl")
                        .HasColumnType("double precision")
                        .HasColumnName("total_pnl");

                    b.HasKey("Id");

                    b.ToTable("portfolio_snapshots", (string)null);
                });

            modelBuilder.Entity("TradingProject.Persistence.Domain.Entities.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AiScore")
                        .HasColumnType("integer")
                        .HasColumnName("ai_score");

                    b.Property<DateTime?>("CloseAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("close_at");

                    b.Property<double?>("ClosePrice")
                        .HasColumnType("double precision")
                        .HasColumnName("close_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("Pnl")
                        .HasColumnType("double precision")
                        .HasColumnName("pnl");

                    b.Property<double?>("PnlPct")
                        .HasColumnType("double precision")
                        .HasColumnName("pnl_pct");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("side");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<double?>("StopLoss")
                        .HasColumnType("double precision")
                        .HasColumnName("stop_loss");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.Property<double?>("TakeProfit")
                        .HasColumnType("double precision")
                        .HasColumnName("take_profit");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("trades", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
